FROM python:3.12.10

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# dev: оставляем инструменты сборки для локальной разработки
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev git \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "run_bot.py"]
